PST-21935-fix-performance-and-product-grid
lengow/plugin-shopware6 pull request #16
Opened 2024-11-19 14:38 UTC by michaelmaslengow

Fix product grid - get product count in toolbox page - export with stream 0
Fix style and translation in order page

[PST-21935](https://lengow.atlassian.net/browse/PST-21935)

2024-11-20 14:45 UTC, arnaud-hours requested changes

2024-11-20 14:53 UTC, michaelmaslengow commented on src/Resources/app/administration/src/module/lengow-connector/page/lgw-product-list/index.js
> +            const test = this.currencies
My bad

2024-12-16 09:07 UTC, alherlengow approved these changes

2024-12-16 15:46 UTC, arnaud-hours approved these changes

2024-12-16 16:08 UTC, merged